-- =============================================================================
-- schema-supabase.sql — À exécuter une fois dans le SQL Editor de Supabase
-- =============================================================================

create table refuges (
  id text primary key,
  nom text not null,
  lat double precision not null,
  lon double precision not null,
  altitude integer,
  region text,
  departement text,
  places text,
  eau text,
  bois text,
  eau_mois integer[],
  type_num integer,
  categorie text,
  description text,
  lien text,
  modifie boolean not null default false,
  origine jsonb,              -- copie des valeurs d'origine, pour permettre un "réinitialiser"
  maj_le timestamptz not null default now()
);

-- Active la sécurité au niveau des lignes (obligatoire pour exposer la table via l'API publique)
alter table refuges enable row level security;

-- Tout le monde peut lire
create policy "lecture publique" on refuges
  for select using (true);

-- Tout le monde peut modifier un lieu existant (pas de compte requis)
create policy "edition publique" on refuges
  for update using (true) with check (true);

-- Pas de policy insert/delete → seul le script d'import (avec la clé service_role,
-- qui contourne RLS) peut créer ou supprimer des lignes. Le public ne peut qu'éditer.

-- SAUF : un compte connecté peut proposer un NOUVEAU lieu (formulaire "Ajouter
-- un refuge"). Toujours pas de suppression possible.
create policy "creation par compte connecte" on refuges
  for insert with check (auth.uid() is not null);


-- =============================================================================
-- Colonnes complémentaires (données croisées depuis un export CSV externe —
-- voir outils/completer-donnees-csv.mjs). À exécuter une fois.
-- =============================================================================
alter table refuges add column if not exists ville text;
alter table refuges add column if not exists cap_ete integer;
alter table refuges add column if not exists cap_hiver integer;
alter table refuges add column if not exists cheminee text;
alter table refuges add column if not exists couchage text;
alter table refuges add column if not exists rando text;

-- La colonne "places" (générique) est remplacée par cap_ete / cap_hiver
-- (plus précis, issus du CSV complémentaire). À exécuter une fois.
alter table refuges drop column if exists places;


-- =============================================================================
-- Formulaire de contact (mentions légales) — écriture publique, lecture
-- réservée à l'admin (toi, via le Dashboard Supabase, jamais exposée sur le
-- site). Évite de publier ton email en clair sur la page mentions légales.
-- =============================================================================

create table contacts (
  id bigint generated by default as identity primary key,
  nom text,
  email text not null,
  message text not null,
  cree_le timestamptz not null default now()
);

alter table contacts enable row level security;

-- Tout le monde peut envoyer un message
create policy "envoi public" on contacts
  for insert with check (true);

-- Pas de policy select : personne (même connecté) ne peut lire les messages
-- via l'API publique. Toi seul les vois, via Supabase → Table Editor →
-- contacts (le Dashboard passe par la clé service_role qui contourne RLS).


-- =============================================================================
-- Historique des passages (commentaires + balises laissés sur un refuge)
-- Partagé entre tous les visiteurs, comme la table refuges.
-- =============================================================================

create table passages (
  id bigint generated by default as identity primary key,
  refuge_id text not null references refuges(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  date text not null,
  commentaire text,
  balises text[],
  cree_le timestamptz not null default now()
);

alter table passages enable row level security;

-- Tout le monde peut lire l'historique (utile pour voir l'état récent d'un refuge)
create policy "lecture publique passages" on passages
  for select using (true);

-- Seuls les comptes connectés peuvent ajouter un passage, et seulement en
-- leur propre nom (impossible de poster au nom de quelqu'un d'autre)
create policy "ajout par compte connecte" on passages
  for insert with check (auth.uid() = user_id);

-- Chacun peut supprimer SES PROPRES passages, jamais ceux des autres
create policy "suppression par l'auteur" on passages
  for delete using (auth.uid() = user_id);

